### ISSUE TITLE
macOS build broken: SessionTreeMemorySampler calls Linux-only fns without cfg guard (E0425)

### ISSUE THREAD

**Issue by aider4ryder** [RyderFreeman4Logos/cli-sub-agent#1642]
## Summary

The macOS build is broken: `SessionTreeMemorySampler` (struct + impl) in
`crates/csa-session/src/process_tree_memory.rs` is **not** `#[cfg]`-gated, but its
methods call three `#[cfg(target_os = "linux")]`-only helpers. On non-Linux targets
those functions don't exist → `error[E0425]`. This reds the **macOS Test** CI job and
is a pre-existing baseline (`main` is red independently of any open PR).

## Evidence

CI run 26600457728, job `Test (macos-latest)`, toolchain `stable-aarch64-apple-darwin`:

```
error[E0425]: cannot find function `read_process_control_group` in this scope
  --> crates/csa-session/src/process_tree_memory.rs:28:34
error[E0425]: cannot find function `read_memory_current_bytes` in this scope
  --> crates/csa-session/src/process_tree_memory.rs:38:32
error[E0425]: cannot find function `sample_process_tree_rss_mb` in this scope
  --> crates/csa-session/src/process_tree_memory.rs:43:9
warning: unused imports: `HashSet` and `VecDeque`  --> .../process_tree_memory.rs:1:24
warning: unused import: `std::fs`                   --> .../process_tree_memory.rs:2:5
error: could not compile `csa-session` (lib) due to 3 previous errors; 2 warnings emitted
```

## Root cause

- Helpers `read_memory_current_bytes` (L69), `sample_process_tree_rss_mb` (L77),
  `read_process_control_group` (L107) are all `#[cfg(target_os = "linux")]`.
- `SessionTreeMemorySampler` struct (L12) + `impl` `new()` / `sample_rss_mb()` (L17-45)
  have **no** cfg attribute and call those helpers unconditionally.
- The sibling fn `session_tree_rss_mb` (L52) handles portability correctly with a
  `#[cfg(not(target_os = "linux"))]` early-return + `#[cfg(target_os = "linux")]` body —
  the struct/impl path was simply missed.
- Imports `HashSet`/`VecDeque`/`std::fs` (L1-2) are used only by Linux-gated code → unused
  warnings on macOS.

Introduced by #995 (commits 4418589c / dcb48784).

## Suggested fix

Gate the whole sampler behind `#[cfg(target_os = "linux")]` (struct + impl + the
Linux-only imports), since it is only ever constructed from Linux-gated call sites; OR add
`#[cfg(not(target_os = "linux"))]` stubs mirroring `session_tree_rss_mb`. Verify with a
cross `cargo check --target aarch64-apple-darwin` (or `x86_64-apple-darwin`).

## Scope note

Per maintainer policy, macOS-only CI red does not block Linux-green merges, so this is
filed rather than folded into an unrelated PR. The Linux-clippy half of the same red
baseline (`clippy::manual_checked_ops`) is fixed in #1641; the structural toolchain-drift
cause is filed separately.
